
package au.edu.unsw.soacourse.topdown;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-18T22:36:50.379+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "visualiseMarketFault", targetNamespace = "http://topdown.soacourse.unsw.edu.au")
public class VisualiseMarketFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.topdown.ServiceFaultType visualiseMarketFault;

    public VisualiseMarketFaultMsg() {
        super();
    }
    
    public VisualiseMarketFaultMsg(String message) {
        super(message);
    }
    
    public VisualiseMarketFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VisualiseMarketFaultMsg(String message, au.edu.unsw.soacourse.topdown.ServiceFaultType visualiseMarketFault) {
        super(message);
        this.visualiseMarketFault = visualiseMarketFault;
    }

    public VisualiseMarketFaultMsg(String message, au.edu.unsw.soacourse.topdown.ServiceFaultType visualiseMarketFault, Throwable cause) {
        super(message, cause);
        this.visualiseMarketFault = visualiseMarketFault;
    }

    public au.edu.unsw.soacourse.topdown.ServiceFaultType getFaultInfo() {
        return this.visualiseMarketFault;
    }
}
